module.exports = {
  entryPoints: ["src/index.ts", "src/types.ts"],
  out: "docs/api",
  name: "Auth Library API Documentation",
  includeVersion: true,
  exclude: ["**/*.test.ts", "**/__tests__/**/*", "node_modules"],
  excludePrivate: true,
  excludeProtected: false,
  excludeInternal: true,
  documentationEntryPoint: "src/index.ts",
  plugin: [],
  theme: "default",
  readme: "README.md",
  titleLink: "https://github.com/your-org/auth",
  gitRevision: "main",
  gitRemote: "origin",
  sourceLinkTemplate: "https://github.com/your-org/auth/blob/{gitRevision}/{path}#L{line}",
  tsconfig: "tsconfig.typedoc.json",
  validation: {
    notExported: true,
    invalidLink: true,
    notDocumented: false,
  },
  visibilityFilters: {
    protected: false,
    private: false,
    inherited: true,
    external: false,
  },
  navigationLinks: {
    GitHub: "https://github.com/your-org/auth",
    Discord: "https://discord.gg/your-discord",
  },
  customCss: undefined,
  searchInComments: true,
  sort: ["source-order", "required-first", "visibility"],
  textContentMappings: {
    "title.memberPage": "{name} | Auth Library",
  },
};