import type { AuthStrategy } from "./strategy";

/**
 * User profile stored in the database.
 * Users implement storage for this interface.
 */
export interface AuthUser {
	/** Unique user ID (generated by storage) */
	id: string;
	/** Username (null if strategy doesn't require it) */
	username: string | null;
	/** Email address (null if strategy doesn't require it) */
	email: string | null;
	/** Password hash (managed by LocalPasswordHasher) */
	passwordHash: string;
	/** User roles */
	roles: string[];
	/** Account creation timestamp */
	createdAt: Date;
	/** Last update timestamp */
	updatedAt: Date;
}

/**
 * Data for creating a new credentials user.
 * Password hash is computed internally by CredentialsClient when registering.
 */
export interface CreateCredentialsUserData {
	username?: string;
	email?: string;
	/** Password hash — computed by CredentialsClient during registration, optional when calling register() */
	passwordHash?: string;
	roles?: string[];
}

/**
 * Identifier used for login.
 * Which fields are required depends on the strategy.
 */
export interface AuthUserIdentifier {
	username?: string;
	email?: string;
}

/**
 * Result of a successful credentials authentication.
 */
export interface CredentialsAuthResult {
	/** The authenticated user */
	user: AuthUser;
	/** JWT session token */
	token: string;
}

/**
 * Configuration for CredentialsClient.
 */
export interface CredentialsClientConfig {
	/** Authentication strategy */
	strategy: AuthStrategy;
	/** JWT session secret */
	secret: string;
	/** Token expiration (default: "7d") */
	expiresIn?: string | number;
	/** Cookie name (default: "credentials-auth-session") */
	cookieName?: string;
	/** Cookie path (default: "/") */
	cookiePath?: string;
	/** HttpOnly cookie flag (default: true) */
	httpOnly?: boolean;
	/** Secure cookie flag (default: false) */
	secure?: boolean;
	/** SameSite cookie policy (default: "lax") */
	sameSite?: "lax" | "strict" | "none";
	/** Roles assigned to new users (default: ["user"]) */
	defaultRoles?: string[];
}

/**
 * Internal processed config with all defaults applied.
 */
export interface InternalCredentialsConfig {
	strategy: AuthStrategy;
	secret: string;
	expiresIn: string | number;
	cookieName: string;
	cookiePath: string;
	httpOnly: boolean;
	secure: boolean;
	sameSite: "lax" | "strict" | "none";
	defaultRoles: string[];
}