/**
 * Self-contained credentials authentication module.
 *
 * This file inlines ALL credentials authentication logic — types, errors,
 * JWT helpers, cookie helpers, brute-force protection, the CredentialsClient,
 * and the HTTP handlers — so it has ZERO imports from `../standalone/*` or
 * `../core/credentials/*`. The only external dependency is `jose` for JWT.
 *
 * Public API:
 *   - `credentials(options)` factory function (main entry)
 *   - All types the factory uses (AuthUser, PasswordHasher, AuthUserStorage, etc.)
 */

import { jwtVerify, SignJWT } from "jose";

// ============================================================================
// SECTION 1 — Strategy enum (inlined from core/credentials/strategy.ts)
// ============================================================================

/**
 * Authentication strategy configuration.
 *
 * Determines which identifier(s) are required for user registration and login.
 */
export enum AuthStrategy {
	/**
	 * Username-only authentication.
	 * - Registration requires: username, password
	 * - Login requires: username, password
	 * - Email is optional and not used for authentication
	 */
	UsernameOnly = "username-only",

	/**
	 * Email-only authentication.
	 * - Registration requires: email, password
	 * - Login requires: email, password
	 * - Username is optional and not used for authentication
	 */
	EmailOnly = "email-only",

	/**
	 * Combined username and email authentication.
	 * - Registration requires: username, email, password
	 * - Login accepts: username OR email, plus password
	 * - Both username and email are unique identifiers
	 */
	UsernameEmail = "username-email",
}

// ============================================================================
// SECTION 2 — Types (inlined from core/credentials/types.ts)
// ============================================================================

/**
 * User profile stored in the database.
 * Users implement storage for this interface.
 */
export interface AuthUser {
	/** Unique user ID (generated by storage) */
	id: string;
	/** Username (null if strategy doesn't require it) */
	username: string | null;
	/** Email address (null if strategy doesn't require it) */
	email: string | null;
	/** Password hash (managed by PasswordHasher) */
	passwordHash: string;
	/** User roles */
	roles: string[];
	/** Account creation timestamp */
	createdAt: Date;
	/** Last update timestamp */
	updatedAt: Date;
}

/**
 * Data for creating a new credentials user.
 * Password hash is computed internally by CredentialsClient when registering.
 */
export interface CreateCredentialsUserData {
	username?: string;
	email?: string;
	/** Password hash — computed by CredentialsClient during registration, optional when calling register() */
	passwordHash?: string;
	roles?: string[];
}

/**
 * Identifier used for login.
 * Which fields are required depends on the strategy.
 */
export interface AuthUserIdentifier {
	username?: string;
	email?: string;
}

/**
 * Result of a successful credentials authentication.
 */
export interface CredentialsAuthResult {
	/** The authenticated user */
	user: AuthUser;
	/** JWT session token */
	token: string;
}

/**
 * Configuration for CredentialsClient.
 */
export interface CredentialsClientConfig {
	/** Authentication strategy */
	strategy: AuthStrategy;
	/** JWT session secret */
	secret: string;
	/** Token expiration (default: "7d") */
	expiresIn?: string | number;
	/** Cookie name (default: "credentials-auth-session") */
	cookieName?: string;
	/** Cookie path (default: "/") */
	cookiePath?: string;
	/** HttpOnly cookie flag (default: true) */
	httpOnly?: boolean;
	/** Secure cookie flag (default: false) */
	secure?: boolean;
	/** SameSite cookie policy (default: "lax") */
	sameSite?: "lax" | "strict" | "none";
	/** Roles assigned to new users (default: ["user"]) */
	defaultRoles?: string[];
}

/**
 * Internal processed config with all defaults applied.
 */
export interface InternalCredentialsConfig {
	strategy: AuthStrategy;
	secret: string;
	expiresIn: string | number;
	cookieName: string;
	cookiePath: string;
	httpOnly: boolean;
	secure: boolean;
	sameSite: "lax" | "strict" | "none";
	defaultRoles: string[];
}

// ============================================================================
// SECTION 3 — Hasher interface (inlined from core/credentials/hasher.ts)
// ============================================================================

/**
 * Password hashing interface for credentials authentication.
 * Users implement this to use their preferred hashing algorithm.
 */
export interface PasswordHasher {
	/** Hash a plain-text password */
	hash(password: string): Promise<string>;
	/** Verify a password against a hash */
	verify(password: string, hash: string): Promise<boolean>;
}

// ============================================================================
// SECTION 4 — Storage interface (inlined from core/credentials/storage.ts)
// ============================================================================

/**
 * Storage interface for credentials authentication.
 * Users implement this to persist auth users in their database.
 */
export interface AuthUserStorage {
	/** Find a user by username */
	findByUsername(username: string): Promise<AuthUser | null>;
	/** Find a user by email */
	findByEmail(email: string): Promise<AuthUser | null>;
	/** Find a user by ID */
	findById(id: string): Promise<AuthUser | null>;
	/** Create a new user */
	create(
		data: Omit<AuthUser, "id" | "createdAt" | "updatedAt">,
	): Promise<AuthUser>;
	/** Update user data */
	update(userId: string, data: Partial<AuthUser>): Promise<AuthUser>;
	/** Delete a user */
	delete(userId: string): Promise<void>;
}

// ============================================================================
// SECTION 5 — Error classes (inlined from core/credentials/errors.ts)
// ============================================================================

/**
 * Base error for the auth error hierarchy.
 * Inlined from core/errors.ts so this file is fully self-contained.
 */
export class DiscordAuthError extends Error {
	readonly code: string;
	readonly cause?: Error;
	readonly statusCode?: number;

	constructor(
		code: string,
		message: string,
		options?: { cause?: Error; statusCode?: number },
	) {
		super(message);
		this.code = code;
		this.cause = options?.cause;
		this.statusCode = options?.statusCode;
		this.name = this.constructor.name;
		if (typeof Error.captureStackTrace === "function") {
			Error.captureStackTrace(this, this.constructor);
		}
	}
}

/** Base error for all credentials auth errors */
export class CredentialsAuthError extends DiscordAuthError {}

/** Username is already taken */
export class UsernameTakenError extends CredentialsAuthError {
	constructor(
		message = "Username is already taken",
		options?: { cause?: Error },
	) {
		super("USERNAME_TAKEN", message, {
			statusCode: 409,
			cause: options?.cause,
		});
	}
}

/** Email is already taken */
export class EmailTakenError extends CredentialsAuthError {
	constructor(message = "Email is already taken", options?: { cause?: Error }) {
		super("EMAIL_TAKEN", message, { statusCode: 409, cause: options?.cause });
	}
}

/** Invalid credentials (wrong password or user not found) */
export class InvalidCredentialsError extends CredentialsAuthError {
	constructor(message = "Invalid credentials", options?: { cause?: Error }) {
		super("INVALID_CREDENTIALS", message, {
			statusCode: 401,
			cause: options?.cause,
		});
	}
}

/** User not found */
export class UserNotFoundError extends CredentialsAuthError {
	constructor(message = "User not found", options?: { cause?: Error }) {
		super("USER_NOT_FOUND", message, {
			statusCode: 404,
			cause: options?.cause,
		});
	}
}

/** Validation error (missing required fields based on auth strategy) */
export class CredentialsValidationError extends CredentialsAuthError {
	constructor(message = "Validation failed", options?: { cause?: Error }) {
		super("CREDENTIALS_VALIDATION_ERROR", message, {
			statusCode: 400,
			cause: options?.cause,
		});
	}
}

// ============================================================================
// SECTION 6 — Brute force protection (inlined from core/brute-force.ts)
// ============================================================================

/**
 * Brute force protection configuration.
 * Inlined from core/types.ts.
 */
export interface BruteForceConfig {
	enabled: boolean;
	maxAttempts: number;
	windowMs: number;
	blockDurationMs: number;
	storage?: BruteForceStorage;
}

/**
 * Storage interface for brute force protection.
 * Inlined from core/types.ts.
 */
export interface BruteForceStorage {
	increment(key: string, windowMs: number): Promise<number>;
	isBlocked(key: string): Promise<boolean>;
	reset(key: string): Promise<void>;
	block(key: string, durationMs: number): Promise<void>;
	getCount(key: string): Promise<number>;
}

/**
 * Simple in-memory brute force storage implementation.
 */
export class MemoryBruteForceStorage implements BruteForceStorage {
	private attempts = new Map<string, { count: number; resetAt: number }>();
	private blockedUntil = new Map<string, number>();

	async increment(key: string, windowMs: number): Promise<number> {
		const now = Date.now();
		const existing = this.attempts.get(key);
		if (!existing || now > existing.resetAt) {
			this.attempts.set(key, { count: 1, resetAt: now + windowMs });
			return 1;
		}
		existing.count++;
		return existing.count;
	}

	async isBlocked(key: string): Promise<boolean> {
		const until = this.blockedUntil.get(key);
		if (!until) return false;
		if (Date.now() > until) {
			this.blockedUntil.delete(key);
			return false;
		}
		return true;
	}

	async reset(key: string): Promise<void> {
		this.attempts.delete(key);
		this.blockedUntil.delete(key);
	}

	async block(key: string, durationMs: number): Promise<void> {
		this.blockedUntil.set(key, Date.now() + durationMs);
	}

	async getCount(key: string): Promise<number> {
		const existing = this.attempts.get(key);
		if (!existing || Date.now() > existing.resetAt) return 0;
		return existing.count;
	}
}

/**
 * Brute force protection — IP-based rate limiting for login attempts.
 * Inlined from core/brute-force.ts.
 */
export class BruteForceProtection {
	private config: Required<Omit<BruteForceConfig, "storage">>;
	private storage: BruteForceStorage;

	constructor(config: BruteForceConfig, storage?: BruteForceStorage) {
		this.config = {
			enabled: config.enabled ?? true,
			maxAttempts: config.maxAttempts ?? 5,
			windowMs: config.windowMs ?? 15 * 60 * 1000,
			blockDurationMs: config.blockDurationMs ?? 30 * 60 * 1000,
		};
		this.storage = storage ?? config.storage ?? new MemoryBruteForceStorage();
	}

	async recordAttempt(key: string, success: boolean): Promise<void> {
		if (!this.config.enabled) return;

		if (success) {
			await this.storage.reset(key);
			return;
		}

		const count = await this.storage.increment(key, this.config.windowMs);
		if (count > this.config.maxAttempts) {
			await this.storage.block(key, this.config.blockDurationMs);
		}
	}

	async isBlocked(key: string): Promise<boolean> {
		if (!this.config.enabled) return false;
		return this.storage.isBlocked(key);
	}

	async getRemainingAttempts(key: string): Promise<number> {
		if (!this.config.enabled) return this.config.maxAttempts;
		const blocked = await this.storage.isBlocked(key);
		if (blocked) return 0;
		const count = await this.storage.getCount(key);
		return Math.max(0, this.config.maxAttempts - count);
	}

	async reset(key: string): Promise<void> {
		if (!this.config.enabled) return;
		await this.storage.reset(key);
	}

	static extractKey(request: Request): string {
		const ip =
			request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
			request.headers.get("x-real-ip") ??
			"unknown";
		const userAgent =
			request.headers.get("user-agent")?.slice(0, 50) ?? "unknown";
		return `${ip}:${userAgent}`;
	}
}

// ============================================================================
// SECTION 7 — JWT helpers (inlined from standalone/jwt.ts)
// ============================================================================

/**
 * Encode a string secret into a Uint8Array key for jose.
 */
function secretToKey(secret: string): Uint8Array {
	return new TextEncoder().encode(secret);
}

/**
 * Sign a JWT payload with HS256.
 * Inlined from standalone/jwt.ts.
 */
async function signToken(
	payload: Record<string, unknown>,
	secret: string,
	expiresIn: string | number = "7d",
): Promise<string> {
	const exp = typeof expiresIn === "number" ? `${expiresIn}s` : expiresIn;

	return new SignJWT(payload)
		.setProtectedHeader({ alg: "HS256" })
		.setIssuedAt()
		.setExpirationTime(exp)
		.sign(secretToKey(secret));
}

/**
 * Verify a JWT token and return its payload, or null if invalid/expired.
 * Inlined from standalone/jwt.ts.
 */
async function verifyToken<T extends Record<string, unknown>>(
	token: string,
	secret: string,
): Promise<T | null> {
	try {
		const { payload } = await jwtVerify(token, secretToKey(secret));
		return payload as T;
	} catch {
		return null;
	}
}

// ============================================================================
// SECTION 8 — Cookie helpers (inlined from standalone/cookies.ts)
// ============================================================================

/**
 * Parse the Cookie header from a Request into a key/value map.
 * Inlined from standalone/cookies.ts.
 */
function parseCookies(request: Request): Record<string, string> {
	const cookieHeader = request.headers.get("cookie") ?? "";
	const cookies: Record<string, string> = {};
	for (const pair of cookieHeader.split(";")) {
		const [key, ...rest] = pair.split("=");
		if (key) {
			cookies[key.trim()] = rest.join("=").trim();
		}
	}
	return cookies;
}

/**
 * Options for creating a session cookie.
 */
interface SessionCookieOptions {
	maxAge?: number;
	path?: string;
	httpOnly?: boolean;
	secure?: boolean;
	sameSite?: "lax" | "strict" | "none";
}

/**
 * Build a Set-Cookie header value for a session cookie.
 * Inlined from standalone/cookies.ts.
 */
function createSessionCookie(
	name: string,
	value: string,
	options: SessionCookieOptions = {},
): string {
	const parts = [`${name}=${value}`];

	if (options.maxAge) parts.push(`Max-Age=${options.maxAge}`);
	if (options.path) parts.push(`Path=${options.path}`);
	if (options.httpOnly) parts.push("HttpOnly");
	if (options.secure) parts.push("Secure");
	if (options.sameSite) parts.push(`SameSite=${options.sameSite}`);

	return parts.join("; ");
}

/**
 * Build a Set-Cookie header value that clears (expires) a session cookie.
 * Inlined from standalone/cookies.ts.
 */
function clearSessionCookie(
	name: string,
	options: {
		path?: string;
		httpOnly?: boolean;
		secure?: boolean;
		sameSite?: "lax" | "strict" | "none";
	} = {},
): string {
	const parts = [
		`${name}=`,
		"Max-Age=0",
		"Expires=Thu, 01 Jan 1970 00:00:00 GMT",
	];

	if (options.path) parts.push(`Path=${options.path}`);
	if (options.httpOnly) parts.push("HttpOnly");
	if (options.secure) parts.push("Secure");
	if (options.sameSite) parts.push(`SameSite=${options.sameSite}`);

	return parts.join("; ");
}

// ============================================================================
// SECTION 9 — CredentialsClient (inlined from core/credentials/client.ts)
// ============================================================================

/**
 * Core credentials authentication client.
 * Handles registration and login logic for username/password auth.
 */
export class CredentialsClient {
	private config: InternalCredentialsConfig;
	private storage: AuthUserStorage;
	private hasher: PasswordHasher;
	private bruteForce: BruteForceProtection;

	constructor(
		config: CredentialsClientConfig,
		storage: AuthUserStorage,
		hasher: PasswordHasher,
		bruteForceConfig?: Partial<BruteForceConfig>,
	) {
		this.config = {
			strategy: config.strategy,
			secret: config.secret,
			expiresIn: config.expiresIn ?? "7d",
			cookieName: config.cookieName ?? "credentials-session",
			cookiePath: config.cookiePath ?? "/",
			httpOnly: config.httpOnly ?? true,
			secure: config.secure ?? false,
			sameSite: config.sameSite ?? "lax",
			defaultRoles: config.defaultRoles ?? ["user"],
		};
		this.storage = storage;
		this.hasher = hasher;
		this.bruteForce = new BruteForceProtection({
			enabled: true,
			maxAttempts: 5,
			windowMs: 15 * 60 * 1000,
			blockDurationMs: 30 * 60 * 1000,
			...bruteForceConfig,
		});
	}

	/**
	 * Register a new user.
	 * Validates fields based on strategy, checks uniqueness, hashes password, creates user.
	 */
	async register(
		data: CreateCredentialsUserData & { password: string },
		_request?: Request,
	): Promise<CredentialsAuthResult> {
		// Validate required fields based on strategy
		this.validateRegistrationFields(data);

		// Check uniqueness
		await this.checkUniqueness(data.username, data.email);

		// Hash password
		const passwordHash = await this.hasher.hash(data.password);

		// Create user
		const user = await this.storage.create({
			username: data.username ?? null,
			email: data.email ?? null,
			passwordHash,
			roles: data.roles ?? this.config.defaultRoles,
		});

		// Generate session token
		const token = await this.createSessionToken(user);

		return { user, token };
	}

	/**
	 * Authenticate a user with credentials.
	 * Returns user and session token on success.
	 */
	async login(
		identifier: AuthUserIdentifier,
		password: string,
		request?: Request,
	): Promise<CredentialsAuthResult> {
		// Check brute force
		const bruteForceKey = this.getBruteForceKey(identifier, request);
		if (bruteForceKey) {
			const blocked = await this.bruteForce.isBlocked(bruteForceKey);
			if (blocked) {
				const _remaining =
					await this.bruteForce.getRemainingAttempts(bruteForceKey);
				throw new InvalidCredentialsError(
					`Account temporarily locked. Try again later.`,
				);
			}
		}

		// Find user by identifier
		const user = await this.findUserByIdentifier(identifier);

		// Always verify password even if user not found (timing-safe)
		const dummyHash = user?.passwordHash ?? "$2b$10$dummy";
		const valid = user
			? await this.hasher.verify(password, user.passwordHash)
			: await this.hasher.verify(password, dummyHash);

		if (!user || !valid) {
			// Record failed attempt
			if (bruteForceKey) {
				await this.bruteForce.recordAttempt(bruteForceKey, false);
			}
			throw new InvalidCredentialsError();
		}

		// Record success (resets counter)
		if (bruteForceKey) {
			await this.bruteForce.recordAttempt(bruteForceKey, true);
		}

		// Generate session token
		const token = await this.createSessionToken(user);

		return { user, token };
	}

	/**
	 * Verify a session token and return the user.
	 */
	async verifySession(token: string): Promise<AuthUser | null> {
		const payload = await verifyToken<Record<string, unknown>>(
			token,
			this.config.secret,
		);
		if (!payload) return null;

		const userId = payload.userId as string;
		if (!userId) return null;

		return this.storage.findById(userId);
	}

	/**
	 * Validate registration fields based on strategy.
	 */
	private validateRegistrationFields(
		data: CreateCredentialsUserData & { password: string },
	): void {
		const errors: string[] = [];

		switch (this.config.strategy) {
			case AuthStrategy.UsernameOnly:
				if (!data.username) errors.push("Username is required");
				break;
			case AuthStrategy.EmailOnly:
				if (!data.email) errors.push("Email is required");
				break;
			case AuthStrategy.UsernameEmail:
				if (!data.username) errors.push("Username is required");
				if (!data.email) errors.push("Email is required");
				break;
		}

		if (!data.password || data.password.length < 1) {
			errors.push("Password is required");
		}

		if (errors.length > 0) {
			throw new CredentialsValidationError(errors.join("; "));
		}
	}

	/**
	 * Check uniqueness of username and email.
	 */
	private async checkUniqueness(
		username?: string,
		email?: string,
	): Promise<void> {
		if (username) {
			const existing = await this.storage.findByUsername(username);
			if (existing) throw new UsernameTakenError();
		}

		if (email) {
			const existing = await this.storage.findByEmail(email);
			if (existing) throw new EmailTakenError();
		}
	}

	/**
	 * Find user by identifier based on strategy.
	 */
	private async findUserByIdentifier(
		identifier: AuthUserIdentifier,
	): Promise<AuthUser | null> {
		switch (this.config.strategy) {
			case AuthStrategy.UsernameOnly:
				if (!identifier.username) return null;
				return this.storage.findByUsername(identifier.username);

			case AuthStrategy.EmailOnly:
				if (!identifier.email) return null;
				return this.storage.findByEmail(identifier.email);

			case AuthStrategy.UsernameEmail:
				// Try username first, then email
				if (identifier.username) {
					const user = await this.storage.findByUsername(identifier.username);
					if (user) return user;
				}
				if (identifier.email) {
					return this.storage.findByEmail(identifier.email);
				}
				return null;

			default:
				return null;
		}
	}

	/**
	 * Generate a JWT session token for a user.
	 */
	private async createSessionToken(user: AuthUser): Promise<string> {
		const payload: Record<string, unknown> = {
			userId: user.id,
			roles: user.roles,
		};
		if (user.username) payload.username = user.username;
		if (user.email) payload.email = user.email;

		return signToken(payload, this.config.secret, this.config.expiresIn);
	}

	/**
	 * Build brute force key from identifier and request.
	 */
	private getBruteForceKey(
		identifier: AuthUserIdentifier,
		_request?: Request,
	): string | null {
		// Use a fixed key for now since we want per-identifier limiting
		const id = identifier.username ?? identifier.email ?? "unknown";
		return `credentials-login:${id}`;
	}
}

// ============================================================================
// SECTION 10 — HTTP handlers (inlined from standalone/credentials.ts)
// ============================================================================

/**
 * Context passed to createCredentialsHandlers.
 */
interface CredentialsHandlerContext {
	client: CredentialsClient;
}

/**
 * Build a JSON Response with the given status.
 */
function jsonResponse(data: unknown, status = 200): Response {
	return new Response(JSON.stringify(data), {
		status,
		headers: { "Content-Type": "application/json; charset=utf-8" },
	});
}

/**
 * Build a 302 redirect Response, optionally setting cookies.
 */
function redirectResponse(url: string, cookies?: string[]): Response {
	const headers = new Headers();
	headers.set("Location", url);
	if (cookies) {
		for (const c of cookies) headers.append("Set-Cookie", c);
	}
	return new Response(null, { status: 302, headers });
}

/**
 * Convert an error into an appropriate HTTP Response.
 */
function errorResponse(error: unknown): Response {
	if (error instanceof CredentialsAuthError) {
		return jsonResponse(
			{ error: error.message, code: error.code },
			error.statusCode ?? 500,
		);
	}
	return jsonResponse({ error: "Internal server error" }, 500);
}

/**
 * Strip the passwordHash from an AuthUser for safe client responses.
 */
function getSafeUser(user: AuthUser): Record<string, unknown> {
	const { passwordHash: _, ...safe } = user;
	return safe;
}

/**
 * Create the four credentials HTTP handlers (register, login, logout, me).
 * Inlined from standalone/credentials.ts.
 */
function createCredentialsHandlers(ctx: CredentialsHandlerContext) {
	const { client } = ctx;

	const cookieName = "credentials-session";
	const cookiePath = "/";
	const sameSite: "lax" = "lax";
	const secure = false;
	const httpOnly = true;
	const expiresIn = "7d";

	const sessionConfig = {
		type: "jwt" as const,
		secret: "",
		cookieName,
		cookiePath,
		sameSite,
		secure,
		httpOnly,
		expiresIn,
	};

	async function handleRegister(request: Request): Promise<Response> {
		if (request.method !== "POST") {
			return jsonResponse({ error: "Method not allowed" }, 405);
		}

		let body: Record<string, unknown>;
		try {
			body = await request.json();
		} catch {
			return jsonResponse({ error: "Invalid JSON body" }, 400);
		}

		try {
			const result = await client.register(
				{
					username: body.username as string | undefined,
					email: body.email as string | undefined,
					password: body.password as string,
				},
				request,
			);

			const cookie = createSessionCookie(
				cookieName,
				result.token,
				sessionConfig,
			);

			return redirectResponse("/auth/credentials/me", [cookie]);
		} catch (error) {
			return errorResponse(error);
		}
	}

	async function handleLogin(request: Request): Promise<Response> {
		if (request.method !== "POST") {
			return jsonResponse({ error: "Method not allowed" }, 405);
		}

		let body: Record<string, unknown>;
		try {
			body = await request.json();
		} catch {
			return jsonResponse({ error: "Invalid JSON body" }, 400);
		}

		try {
			const result = await client.login(
				{
					username: body.username as string | undefined,
					email: body.email as string | undefined,
				},
				body.password as string,
				request,
			);

			const cookie = createSessionCookie(
				cookieName,
				result.token,
				sessionConfig,
			);

			return redirectResponse("/", [cookie]);
		} catch (error) {
			return errorResponse(error);
		}
	}

	async function handleLogout(_request: Request): Promise<Response> {
		const clearCookie = clearSessionCookie(cookieName, sessionConfig);
		return redirectResponse("/", [clearCookie]);
	}

	async function handleMe(request: Request): Promise<Response> {
		const cookies = parseCookies(request);
		const sessionToken = cookies[cookieName];

		if (!sessionToken) {
			return jsonResponse({ error: "Unauthorized" }, 401);
		}

		try {
			const user = await client.verifySession(sessionToken);
			if (!user) {
				return jsonResponse({ error: "Invalid session" }, 401);
			}
			return jsonResponse(getSafeUser(user));
		} catch {
			return jsonResponse({ error: "Invalid session" }, 401);
		}
	}

	return {
		handleRegister,
		handleLogin,
		handleLogout,
		handleMe,
	};
}

// ============================================================================
// SECTION 11 — Public factory (credentials)
// ============================================================================

/**
 * Configuration for the credentials factory.
 */
export interface CredentialsConfig {
	/** Authentication strategy */
	strategy: CredentialsClientConfig["strategy"];
	/** JWT session configuration */
	session: {
		secret: string;
		expiresIn?: string | number;
		cookieName?: string;
	};
	/** User storage implementation */
	storage: AuthUserStorage;
	/** Password hasher implementation */
	hasher: PasswordHasher;
	/** Optional brute force protection */
	bruteForce?: Partial<BruteForceConfig>;
	/** Cookie path (default: "/") */
	cookiePath?: string;
	/** HttpOnly cookie flag (default: true) */
	httpOnly?: boolean;
	/** Secure cookie flag (default: false) */
	secure?: boolean;
	/** SameSite cookie policy (default: "lax") */
	sameSite?: "lax" | "strict" | "none";
}

/**
 * Result of the credentials factory — handlers + session + route guard.
 */
export interface CredentialsResult {
	/** Register a new user */
	handleRegister: (request: Request) => Promise<Response>;
	/** Login with username/email + password */
	handleLogin: (request: Request) => Promise<Response>;
	/** Logout (clear session cookie) */
	handleLogout: (request: Request) => Promise<Response>;
	/** Get current user from session */
	handleMe: (request: Request) => Promise<Response>;
	/** Extract and verify a credentials session from a Request */
	getSession: (request: Request) => Promise<AuthUser | null>;
	/** Protect a route handler — returns 401 if not authenticated */
	withAuth: <
		T extends (
			request: Request,
			ctx: { user: AuthUser },
		) => Promise<Response> | Response,
	>(
		handler: T,
	) => (request: Request) => Promise<Response>;
}

/**
 * Thin credentials factory — wraps createCredentialsHandlers + getSession + withAuth.
 *
 * @example
 * ```ts
 * import { credentials } from "@hallaxius/auth"
 *
 * const auth = credentials({
 *   strategy: "username-email",
 *   session: { secret: process.env.JWT_SECRET!, expiresIn: "7d" },
 *   storage: myStorage,
 *   hasher: bcryptHasher,
 * })
 *
 * // Use in route handlers
 * export const POST = auth.handleRegister
 * export const GET = auth.withAuth(async (req, { user }) => {
 *   return Response.json({ username: user.username })
 * })
 * ```
 */
export function credentials(config: CredentialsConfig): CredentialsResult {
	const cookieName = config.session.cookieName ?? "credentials-session";
	const _cookiePath = config.cookiePath ?? "/";
	const _sameSite = config.sameSite ?? "lax";
	const _secure = config.secure ?? false;
	const _httpOnly = config.httpOnly ?? true;

	// Create the underlying CredentialsClient
	const client = new CredentialsClient(
		{
			strategy: config.strategy,
			secret: config.session.secret,
			expiresIn: config.session.expiresIn,
			cookieName,
		},
		config.storage,
		config.hasher,
		config.bruteForce,
	);

	// Create HTTP handlers (register, login, logout, me)
	const handlers = createCredentialsHandlers({ client });

	/**
	 * Extract and verify a credentials session from a Request.
	 * Returns the AuthUser or null if not authenticated.
	 */
	async function getSession(request: Request): Promise<AuthUser | null> {
		const cookies = parseCookies(request);
		const token = cookies[cookieName];
		if (!token) return null;

		const payload = await verifyToken<Record<string, unknown>>(
			token,
			config.session.secret,
		);
		if (!payload) return null;

		// Look up the full user from storage
		const userId = payload.sub ?? payload.id ?? payload.userId;
		if (typeof userId !== "string") return null;

		const user = await config.storage.findById(userId);
		return user ?? null;
	}

	/**
	 * Protect a route handler — returns 401 if not authenticated.
	 */
	function withAuth<
		T extends (
			request: Request,
			ctx: { user: AuthUser },
		) => Promise<Response> | Response,
	>(handler: T): (request: Request) => Promise<Response> {
		return async (request: Request): Promise<Response> => {
			const user = await getSession(request);
			if (!user) {
				return new Response(JSON.stringify({ error: "Unauthorized" }), {
					status: 401,
					headers: { "Content-Type": "application/json" },
				});
			}
			return handler(request, { user });
		};
	}

	return {
		handleRegister: handlers.handleRegister,
		handleLogin: handlers.handleLogin,
		handleLogout: handlers.handleLogout,
		handleMe: handlers.handleMe,
		getSession,
		withAuth,
	};
}
